---
#
# ci/pipeline.yml
#
# Pipeline structure file for a Go Project pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( concat meta.name " Release" ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full URL of the target Concourse CI" ))
  pipeline: (( grab meta.name ))

  git:
    email:  (( param "Please provide the git email for automated commits" ))
    name:   (( param "Please provide the git name for automated commits" ))

  go:
    version: "1.21"
    module:  (( concat "github.com/" meta.github.owner "/" meta.github.repo ))
    cmd_module: (( grab meta.go.module ))
    binary:  (( grab meta.github.repo ))
    force_static_binary: false

  image:
    name: starkandwayne/concourse-go
    tag: (( grab meta.go.version ))
    registry:
      username: (( param "Please set your Docker registry username for your pipeline image" ))
      password: (( param "Please set your Docker registry password for your pipeline image" ))

  aws:
    bucket:      (( concat meta.pipeline "-pipeline" ))
    region_name: us-east-1
    access_key: (( param "Please set your AWS Access Key ID" ))
    secret_key: (( param "Please set your AWS Secret Key ID" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token and specify it here" ))

  slack:
    webhook:      (( param "Please specify your Slack Incoming Webhook Integration URL" ))
    channel:      (( param "Please specify the channel (#name) or user (@user) to send messages to" ))
    username:     concourse
    icon:         https://cl.ly/2F421Y300u07/concourse-logo-blue-transparent.png
    fail_moji:    ":airplane_arriving:"
    success_moji: ":airplane_departure:"
    upset_moji:   ":sadpanda:"
    pipeline_url:  (( concat meta.url "/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}" ))
    fail_link:     (( concat "<" meta.slack.pipeline_url "/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}| Concourse Failure! " meta.slack.upset_moji ">" ))
    fail_text:    '(( concat meta.slack.fail_link " " meta.pipeline ": `${BUILD_JOB_NAME}` job failed" ))'

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - test
      - test-pr
      - rc
      - shipit
      - bump-patch
  - name: versioning
    jobs:
      - major
      - minor

jobs:
  - name: test
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: git, trigger: true }
          - { get: image }
      - task: test
        image: image
        config:
          platform: linux
          inputs:
            - name: git
              path: (( concat "gopath/src/" meta.go.module ))
          caches: [ path: gopath ]
          run:
            path: (( concat "./gopath/src/" meta.go.module "/ci/scripts/test" ))
            args: []
          params:
            MODULE: (( grab meta.go.module ))
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: test-pr
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: git-pull-requests, trigger: true, version: every }
          - { get: image }
      - put: git-pull-requests
        params:
          path: git-pull-requests
          status: PENDING
      - task: test
        image: image
        config:
          platform: linux
          inputs:
            - name: git-pull-requests
              path: (( concat "gopath/src/" meta.go.module ))
          caches: [ path: gopath ]
          run:
            path: (( concat "./gopath/src/" meta.go.module "/ci/scripts/test" ))
            args: []
          params:
            MODULE: (( grab meta.go.module ))
        on_success:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: SUCCESS
        on_failure:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: FAILURE
      - task: pr-success-message
        image: image
        config:
          platform: linux
          inputs:  [ name: git-pull-requests ]
          outputs: [ name: message ]
          run:
            path: bash
            args:
            - -c
            - |
              set -ueo pipefail
              pr_author=$(      < git-pull-requests/.git/resource/author)
              pr_author_email=$(< git-pull-requests/.git/resource/author_email)
              pr_title=$(       < git-pull-requests/.git/resource/title)
              pr_url=$(         < git-pull-requests/.git/resource/url)
              echo "Pull request “_<${pr_url}|${pr_title}>_”" \
                "by *${pr_author:-${pr_author_email}}*" \
                "has passed Golang tests :tada:" \
                "Merge when ready ${SUCCESS_MOJI}:"$'\n'"${pr_url}" \
                > message/body
          params:
            SUCCESS_MOJI: (( grab meta.slack.success_moji ))
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: rc
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: git,     trigger: true, passed: [ test ] }
          - { get: version, params: { pre: rc } }
          - { get: image }
      - task: release-notes
        image: image
        config:
          platform: linux
          inputs: [ name: git ]
          run:
            path: sh
            args:
            - -ce
            - |
              cd git
              if [ -f ci/release_notes.md ]; then
                echo "######   RELEASE NOTES   ###############"
                echo
                cat ci/release_notes.md
                echo
                echo "########################################"
                echo
              else
                echo "NO RELEASE NOTES HAVE BEEN WRITTEN"
                echo "You *might* want to do that before"
                echo "hitting (+) on that shipit job..."
                echo
              fi
      - put: version
        params: { file: version/number }
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: bump-patch
    public: true
    serial: true
    plan:
      - { get: version, trigger: true, params: { bump: patch, pre: rc }, passed: [shipit] } # bump rc + patch, so that subesquent version bumps can trigger a new bump-patch
      - { put: version,                params: { file: version/number} }
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: minor
    public: true
    serial: true
    plan:
      - { get: version, trigger: false, params: { bump: minor } }
      - { put: version,                 params: { file: version/number } }
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: major
    public: true
    serial: true
    plan:
      - { get: version, trigger: false, params: { bump: major } }
      - { put: version,                 params: { file: version/number } }
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

  - name: shipit
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: version, passed: [ rc ], params: { bump: final } }
          - { get: git,     passed: [ rc ] }
          - { get: image }
      - task: release
        image: image
        config:
          platform: linux
          inputs:
            - name: version
            - name: git
              path: (( concat "gopath/src/" meta.go.module ))
          outputs:
            - name: gh
            - name: pushme
            - name: notifications
          caches:
            - path: gopath
          run:
            path: (( concat "./gopath/src/" meta.go.module "/ci/scripts/shipit" ))
            args: []
          params:
            BINARY:       (( grab meta.go.binary ))
            REPO_ROOT:    (( concat "gopath/src/" meta.go.module ))
            VERSION_FROM: version/number
            RELEASE_NAME: (( grab meta.release ))
            RELEASE_ROOT: gh
            REPO_OUT:     pushme
            NOTIFICATION_OUT: notifications
            BRANCH:       (( grab meta.github.branch ))
            GITHUB_OWNER: (( grab meta.github.owner ))
            GITHUB_REPO: (( grab meta.github.repo ))
            CMD_PKG:      (( grab meta.go.cmd_module ))
            STATIC_BINARY:  (( grab meta.go.force_static_binary ))
            GIT_EMAIL:      (( grab meta.git.email ))
            GIT_NAME:       (( grab meta.git.name ))
      - put: version
        params: { bump: final }
      - put: git
        params:
          rebase: true
          repository: pushme/git
      - put: github
        params:
          name:  gh/name
          tag:   gh/tag
          body:  gh/notes.md
          globs: [ gh/artifacts/* ]
      - in_parallel:
        - put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text_file: notifications/message
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))

resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: image
    type: registry-image
    icon: docker
    source:
      repository: (( grab meta.image.name ))
      tag:        (( grab meta.image.tag ))
      username:   (( grab meta.image.registry.username ))
      password:   (( grab meta.image.registry.password ))

  - name: git
    type: git
    icon: github
    source:
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))

  - name: version
    type: semver
    icon: aws
    source:
      driver:            s3
      bucket:            (( grab meta.aws.bucket ))
      region_name:       (( grab meta.aws.region_name ))
      key:               version
      access_key_id:     (( grab meta.aws.access_key ))
      secret_access_key: (( grab meta.aws.secret_key ))
      initial_version:   (( grab meta.initial_version || "0.0.1" ))

  - name: notify
    type: slack-notification
    icon: slack
    source:
      url: (( grab meta.slack.webhook ))

  - name: github
    type: github-release
    icon: github
    source:
      user:         (( grab meta.github.owner ))
      repository:   (( grab meta.github.repo ))
      access_token: (( grab meta.github.access_token ))

  - name: git-pull-requests
    type: pull-request
    icon: github
    source:
      access_token: (( grab meta.github.access_token ))
      repository:   (( concat meta.github.owner "/" meta.github.repo ))
      base_branch:  (( grab meta.github.branch ))
