---
meta:
  name:    humanize-manifest
  release: (( concat meta.name " CLI" ))
  target:  (( grab meta.team ))
  url:     https://ci.gstack.io
  team:    gk-plat-devs

  initial_version: 2.0.0

  go:
    binary: humanize-manifest
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  image:
    name: (( concat meta.private-registry.host "/gstack/gk-ops" ))
    tag:  latest
    registry:
      username: (( grab meta.private-registry.username ))
      password: (( grab meta.private-registry.password ))

  private-registry:
    host:       harbor.ci.gstack.io
    username:   ((private-registry-username))
    password:   ((private-registry-password))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: eu-west-3
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  cloudfoundry-community
    repo:   humanize-manifest
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#oss-pipelines-notifications"

groups:
  - name: bump
    jobs:
      - bump-deps

jobs:
  - name: test
    plan:
      - (( inline ))
      - in_parallel:
          - (( merge on get ))
          - get: golang-alpine
            trigger: true
            passed: [ bump-deps ]

      # NOTICE: we replace all further steps
      - # task: test
        (( prune ))

      - &compile_task
        task: compile
        image: golang-alpine
        config:
          platform: linux
          inputs:
            - name: git
          outputs:
            - name: compiled-binary
          run:
            dir: git
            path: go
            args:
              - build
              - -o
              - ../compiled-binary/humanize-manifest

      - &smpoke_test_task
        task: smoke-test
        image: image
        config:
          platform: linux
          inputs:
            - name: compiled-binary
            - name: git
          run:
            path: bash
            args:
              - -exc
              - |
                export PATH=${PWD}/compiled-binary:${PATH}

                humanize-manifest git/test/fixture.yml > result.yml
                diff -u git/test/expected.yml result.yml

  - name: test-pr
    plan:
      - (( inline ))
      - in_parallel:
          - (( merge on get ))
          - get: golang-alpine
            trigger: true
            passed: [ bump-deps ]

      - {} # put: git-pull-requests

      # We replace the 'task: text' by a block of 2 tasks
      - task:   (( prune ))
        image:  (( prune ))
        config: (( prune ))
        do:
          - *compile_task

          - *smpoke_test_task

  - name: bump-deps
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: weekly, trigger: true }
          - { get: git }
          - { get: gk-automation }
          - { get: golang-alpine }
          - { get: syft }
          - { get: image }

      - task: bump-golang-deps
        image: golang-alpine
        config:
          platform: linux
          inputs:  [ { name: git, path: repo } ]
          outputs:
            - name: repo-bumped
            - name: golang-info
          run:
            path: sh
            args:
            - -ec
            - |
              find "repo" -mindepth 1 -maxdepth 1 -print0 \
                  | xargs -0 -I{} cp -a {} "repo-bumped"
              cd "repo-bumped" || exit 115

              awk '/^go /{print $2}' go.mod > ../golang-info/previous-version
              (
                  set -x
                  go_version=$(
                      go version \
                      | awk '{sub(/go/,"",$3); sub(/\.[[:digit:]]+$/,"",$3); print $3}'
                  )
                  sed -i -Ee "s/^go [[:digit:].]+\$/go ${go_version}/" go.mod
                  go get -t -u ./...
                  go mod tidy

                  echo "${go_version}" > ../golang-info/version
              )

      - task: generate-sboms
        image: syft
        config:
          platform: linux
          inputs:  [ { name: repo-bumped, path: repo } ]
          outputs: [ { name: sboms } ]
          run:
            dir: repo
            path: /syft
            args:
              - .
              - --verbose
              - --select-catalogers=go
              -      --output=syft-json=../sboms/sbom.syft.json
              - --output=cyclonedx-json=../sboms/sbom.cyclonedx.json
              -      --output=spdx-json=../sboms/sbom.spdx.json

      - <<: *compile_task
        input_mapping: { git: repo-bumped }

      - *smpoke_test_task

      - task: generate-messages
        image: image
        config:
          platform: linux
          inputs:  [ name: golang-info ]
          outputs: [ name: messages ]
          run:
            path: bash
            args:
            - -c
            - |
              set -ueo pipefail
              go_prev_ver=$(< golang-info/previous-version)
              go_curr_ver=$(< golang-info/version)

              version_details="${go_curr_ver}"
              if [[ ${go_curr_ver} != ${go_prev_ver} ]]; then
                  version_details="from ${go_prev_ver} to ${go_curr_ver} and its"
              fi
              echo "Update Golang ${version_details} dependencies" \
                  > messages/commit-message

              echo "${PIPELINE_NAME}: successfully bumped Golang ${version_details} dependencies," \
                "with passing tests! :tada:" \
                "<${PIPELINE_URL}|Ship it when ready!> ${SUCCESS_MOJI}" \
                > messages/notif-body
          params:
            SUCCESS_MOJI:  (( grab meta.slack.success_moji ))
            PIPELINE_URL:  (( grab meta.slack.pipeline_url ))
            PIPELINE_NAME: (( grab meta.pipeline ))

      - task: git-commit
        image: image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo:        repo-bumped
          commit-info: messages
        params:
          GIT_COMMIT_NAME:    (( grab meta.git.name ))
          GIT_COMMIT_EMAIL:   (( grab meta.git.email ))
          GIT_DIFF_OPTS:      --color-words

      - put: git
        params:
          repository: repo-committed
          rebase:     true

    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.fail_text ))
    on_success:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text_file: messages/notif-body

  - name: shipit
    plan:
      - (( inline ))
      - in_parallel:
          - (( merge on get ))
          - { get: image, resource: golang-alpine, passed: [ test ] }
      - task: release
        config:
          run:
            path: sh
            args:
              - -ec
              - |
                apk --no-progress add  bash  git  gcc  musl-dev
                export PATH=${PWD}/gopath/bin:${PATH}
                bash "${SHIPIT_SCRIPT}"
          params:
            SHIPIT_SCRIPT: (( concat "./gopath/src/" meta.go.module "/ci/scripts/shipit" ))

resources:

  - name: image
    source:
      tag:               (( prune ))
      semver_constraint: "< 1970" # Avoid YYYYMMDD tags like '20231219'

  - name: version
    source:
      bucket:            (( prune ))
      region_name:       (( prune ))
      key:               (( prune ))
      access_key_id:     (( prune ))
      secret_access_key: (( prune ))
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        (( concat "versions/" meta.pipeline ))
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"

  - name: golang-alpine
    type: registry-image
    icon: docker
    check_every: 24h
    source:
      repository: golang
      variant:    alpine

  - name: git
    check_every: 24h
    webhook_token: ((gk-concourse-webhook-token))

  - name: git-pull-requests
    check_every: 24h
    webhook_token: ((gk-concourse-webhook-token))

  - name: weekly
    type: time
    icon: alarm
    source:
      location: Europe/Paris
      start:    "3:00"
      stop:     "4:30"
      days:     [ Saturday ]

  - name: gk-automation
    type: git
    icon: github
    check_every: 24h
    source:
      uri:         git@github.com:gstackio/gk-automation.git
      branch:      master
      private_key: (( grab meta.github.private_key ))

  - name: syft
    type: registry-image
    source:
      repository: anchore/syft
      variant:    ""
