name: Trigger Concourse pull requests
on: [ push, pull_request ]
jobs:
  trigger-resource-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger resource check
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url:           https://ci.gstack.io
          concourse-team:          gk-plat-devs
          concourse-pipeline:      humanize-manifest
          concourse-resource:      git-pull-requests
          concourse-webhook-token: ${{ secrets.GK_CONCOURSE_WEBHOOK_TOKEN }}
